import './globals.css'
import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Roboto_Slab } from 'next/font/google'

const robotoSlab = Roboto_Slab()

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>{children}</body>
    </html>
  )
}
